### ISSUE TITLE
Cannot install plugin on Apple Silicon macOS (version of capture-website dependency is too old)

### ISSUE THREAD

**Issue by purrloftruth** [tannerdolby/eleventy-plugin-social-img#5]
The version of `capture-website` depended on by this plugin depends on a version of puppeteer that doesn't have an arm64 binary for Chromium, so this plugin won't install on an Apple Silicon Mac. The version of `capture-website` depended on by the plugin is several major versions behind latest, so I'm not sure if there are breaking API changes that would require any sort of rewrite, but for now the plugin isn't able to be used.

Install log:

```
❯ npm install eleventy-plugin-social-img
npm WARN deprecated puppeteer@5.5.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path /Users/ruth/Git/Sites/purrl.org/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! The chromium binary is not available for arm64: 
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  apt-get install chromium-browser
npm ERR! 
npm ERR! /Users/ruth/Git/Sites/purrl.org/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
npm ERR!             throw new Error();
npm ERR!             ^
npm ERR! 
npm ERR! Error
npm ERR!     at /Users/ruth/Git/Sites/purrl.org/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112:19
npm ERR!     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! 
npm ERR! Node.js v18.12.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ruth/.npm/_logs/2022-11-25T18_18_55_419Z-debug-0.log
```

**Comment by tannerdolby** [comment]
@purrloftruth Thank you for bringing this to my attention! I have a M1 chip to test things out so I will work on fixing this today. Expect an update by end of today or within next few days.

**Comment by tannerdolby** [comment]
v1.3.3 is now live! All dependencies are up-to-date and I was able to `npm i eleventy-plugin-social-img` on a M1 chip MBP!

I tested a few of the themes functionality and everything was working, let me know if you encounter any issues and I'm happy to help. Feel free to close this issue if things are resolved, otherwise I'll keep it open until you feel things are functional/fixed.

**Comment by purrloftruth** [comment]
It installs great now, and it does seem to work just fine on default settings. Thank you!
